CREATE DATABASE FENOGENO;
USE FENOGENO;

CREATE TABLE OLHOS(
ID			INTEGER PRIMARY KEY IDENTITY(1,1),
DESCRICAO	VARCHAR(50)
)

INSERT INTO OLHOS
VALUES
('Azul'),
('Castanho'),
('Preto'),
('Verde')

SELECT * FROM OLHOS;

CREATE TABLE CABELO(
ID			INTEGER PRIMARY KEY IDENTITY(1,1),
DESCRICAO	VARCHAR(50)
)

INSERT INTO CABELO
VALUES
('Castanho'),
('Loiro'),
('Preto'),
('Ruivo')

SELECT * FROM CABELO;

CREATE TABLE PELE(
ID				INTEGER PRIMARY KEY IDENTITY(1,1),
DESCRICAO		VARCHAR(50)
)

INSERT INTO PELE
VALUES
('Pele clara'),
('Pele escura')

SELECT * FROM PELE;

CREATE TABLE GRUPO_SANGUINEO(
ID			INTEGER PRIMARY KEY IDENTITY(1,1),
DESCRICAO	VARCHAR(50)
)

INSERT INTO GRUPO_SANGUINEO
VALUES
('A'),
('AB'),
('B'),
('O')

SELECT * FROM GRUPO_SANGUINEO;

CREATE TABLE FATOR_RH(
ID			INTEGER PRIMARY KEY IDENTITY(1,1),
DESCRICAO	VARCHAR(50)
)

INSERT INTO FATOR_RH
VALUES
('+'),
('-')

SELECT * FROM FATOR_RH;

CREATE TABLE ESPECIALISTA(
CRM				INTEGER PRIMARY KEY,
CPF				INTEGER,
NOME			VARCHAR(100),
EMAIL			VARCHAR(50),
TELEFONE		INTEGER,
CURSO_F			VARCHAR(40),
UNIVERSIDADE_C	VARCHAR(40),
DURACAO_C		VARCHAR(10),
ANO_INICIO_C	DATE,
ANO_TERMINO_C	DATE,
AREA_E			VARCHAR(100),
UNIVERSIDADE_E	VARCHAR(40),
DURACAO_E		VARCHAR(10),
ANO_INICIO_E	DATE,
ANO_TERMINO_E	DATE,
FOTO			VARCHAR(1000)
)

SELECT * FROM ESPECIALISTA;

CREATE TABLE NOTICIA(
COD				INTEGER IDENTITY(1,1) PRIMARY KEY ,
TITULO			VARCHAR(70),
DESCRICAO		VARCHAR(150),
CORPO_TEXTO		VARCHAR(MAX),
FOTO			VARCHAR(1000)
)

SELECT * FROM NOTICIA;

CREATE TABLE USUARIO(
ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
NOME			VARCHAR(200),
LOGIN			VARCHAR(100),
SENHA			VARCHAR(10),
EMAIL			VARCHAR(200)
)

SELECT * FROM USUARIO;
SELECT * FROM NOTICIA;