CREATE DATABASE FENOGENO
GO

USE FENOGENO
GO

CREATE TABLE OLHOS(
	ID			INTEGER PRIMARY KEY IDENTITY(1,1),
	DESCRICAO	VARCHAR(50)
)

INSERT INTO OLHOS
VALUES
('Azul'),
('Castanho'),
('Verde');

SELECT * FROM OLHOS;

CREATE TABLE CABELO(
	ID			INTEGER PRIMARY KEY IDENTITY(1,1),
	DESCRICAO	VARCHAR(50)
)

INSERT INTO CABELO
VALUES
('Castanho'),
('Loiro'),
('Preto'),
('Ruivo');

SELECT * FROM CABELO;

CREATE TABLE PELE(
	ID				INTEGER PRIMARY KEY IDENTITY(1,1),
	DESCRICAO		VARCHAR(50)
);

INSERT INTO PELE
VALUES
('Pele clara'),
('Pele escura');

SELECT * FROM PELE;

CREATE TABLE GRUPO_SANGUINEO(
ID			INTEGER PRIMARY KEY IDENTITY(1,1),
DESCRICAO	VARCHAR(50)
)

INSERT INTO GRUPO_SANGUINEO
VALUES
('A'),
('AB'),
('B'),
('O');

SELECT * FROM GRUPO_SANGUINEO;

CREATE TABLE FATOR_RH(
	ID			INTEGER PRIMARY KEY IDENTITY(1,1),
	DESCRICAO	VARCHAR(50)
)

INSERT INTO FATOR_RH
VALUES
('+'),
('-');

SELECT * FROM FATOR_RH;

CREATE TABLE ESPECIALISTA(
	COD				INTEGER IDENTITY(1,1) PRIMARY KEY,
	CRM				VARCHAR(50),
	CPF				VARCHAR(50),
	NOME			VARCHAR(100),
	EMAIL			VARCHAR(250),
	TELEFONE		VARCHAR(30),
	CURSO_F			VARCHAR(40),
	UNIVERSIDADE_C	VARCHAR(40),
	DURACAO_C		VARCHAR(10),
	ANO_INICIO_C	INTEGER,
	ANO_TERMINO_C	INTEGER,
	AREA_E			VARCHAR(100),
	UNIVERSIDADE_E	VARCHAR(40),
	DURACAO_E		VARCHAR(10),
	ANO_INICIO_E	INTEGER,
	ANO_TERMINO_E	INTEGER,
	FOTO			VARCHAR(1000)
);

SELECT * FROM ESPECIALISTA;

CREATE TABLE NOTICIA(
	COD				INTEGER IDENTITY(1,1) PRIMARY KEY ,
	TITULO			VARCHAR(70),
	DESCRICAO		VARCHAR(150),
	CORPO_TEXTO		VARCHAR(MAX),
	FOTO			VARCHAR(1000)
);

SELECT * FROM NOTICIA;

CREATE TABLE USUARIO(
	ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME			VARCHAR(200),
	EMAIL			VARCHAR(200),
	SENHA			VARCHAR(10),
	CIDADE			VARCHAR(500),
	BAIRRO			VARCHAR(500),
	FOTO			VARCHAR(2000),
	ADMINISTRADOR	BIT DEFAULT 0
);

SELECT * FROM USUARIO;
SELECT * FROM NOTICIA;

CREATE TABLE COMENTARIO(
	ID			INTEGER IDENTITY(1,1) PRIMARY KEY,
	ID_NOTICIA	INTEGER REFERENCES NOTICIA(COD),	
	ID_USUARIO	INTEGER REFERENCES USUARIO(ID),
	DATAHORA	DATETIME,
	TEXTO		VARCHAR(MAX)
);

SELECT * FROM COMENTARIO;

CREATE TABLE ANOMALIA(
	ID			INTEGER IDENTITY(1,1) PRIMARY KEY, 
	DESCRICAO	VARCHAR(100)
);

INSERT INTO ANOMALIA
VALUES
('Polidactilia'),
('Doença de Huntington'),
('Doença de Hippel'),
('Daltonismo'),
('Albinismo'),
('Hemofilia');